services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      SECRET: secret
      SESSION_NAME: sessionId
      DATABASE_URL: postgresql://postgres:pass@db:5432/posts
    ports:
      - 3000:3000
    volumes:
      - ./prisma:/usr/src/app/prisma:rw
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=posts
      - POSTGRES_PASSWORD=pass
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
